java_library(
    name = "data",
    srcs = [
        "CognitoClientCredentialsSecret.java",
        "CognitoStackOutputs.java",
        "StackOutputs.java",
    ],
    visibility = [
        "//app/auth/cognito:__subpackages__",
    ],
    deps = [
        "@maven_logos//:com_google_code_gson_gson",
    ],
)
