java_library(
    name = "user",
    srcs = [
        "AuthenticatedUser.java",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@logos//dev/logos/user",
        "@maven_logos//:io_jsonwebtoken_jjwt_api",
    ],
)
