java_library(
	name = "storage",
    srcs = ["StorageService.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//java/core",
        "//dev/logos/service/storage/exceptions",
        "//dev/logos/auth/user",
        "//dev/logos/service",
        "@grpc_java_bzlmod//api",
        "@grpc_java_bzlmod//stub"
    ]
)