java_library(
    name = "type",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//dev/logos/service/storage/pg/exporter/mapper",
        "@com_google_protobuf//:protobuf_java",
        "@maven_logos//:com_squareup_javapoet",
    ],
)