java_library(
    name = "app",
    srcs = [
        "App.java",
        "AppModule.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//dev/logos/service",
        "@io_grpc_grpc_java//api",
        "@io_grpc_grpc_java//stub",
        "@maven_logos//:com_google_inject_guice",
    ],
)
