java_library(
    name = "annotation",
    srcs = [
        "AuthenticationCookieDomain.java",
        "CognitoClientCredentialsSecretArn.java",
        "CognitoUserPoolDomainBaseUrl.java",
        "CognitoUserPoolDomainRedirectUrl.java",
        "CognitoUserPoolDomainSignInUrl.java",
        "CognitoUserPoolId.java",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@maven_logos//:com_google_inject_guice",
    ],
)
