apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: logos-iam-eks-service-account
      containers:
        - name: backend
          image: backend-image:latest
          imagePullPolicy: Always
          env:
            - name: STORAGE_PG_BACKEND_JDBC_URL
              value: jdbc:postgresql://db-rw.logos.dev/logos?usessl=require #&sslmode=verify-full&sslrootcert=/etc/ssl/certs/ca-certificates.crt
            - name: STORAGE_PG_BACKEND_USER
              value: storage
#            - name: SERVER_AUTH_PRIVATE_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: server-auth-key
#                  key: private-key
#                  optional: false
          ports:
            - containerPort: 8081
