java_library(
    name = "pg",
    srcs = glob([
        "*.java",
    ]),
    visibility = [
        "//app:__subpackages__",
        "//dev/logos/stack/bind:__pkg__",
        "//dev/logos/stack/module:__subpackages__",
        "//dev/logos/stack/service/backend:__subpackages__",
        "//dev/logos/stack/service/storage:__subpackages__",
    ],
    deps = [
        "@maven//:javax_inject_javax_inject",
    ],
)
