java_library(
    name = "cookie",
    srcs = [
        "CookieServerInterceptor.java",
    ],
    visibility = ["//app:__subpackages__"],
    deps = [
        "@io_grpc_grpc_java//api",
        "@io_grpc_grpc_java//context",
        "@maven//:com_google_code_gson_gson",
    ],
)
