java_library(
    name = "proto",
    srcs = [
        "ProtoGenerator.java",
    ],
    visibility = [
        "//dev/logos/service/storage/pg/exporter:__subpackages__",
    ],
    deps = [
        "//dev/logos/service/storage/pg",
        "//dev/logos/service/storage/pg/exporter/descriptor",
        "//dev/logos/service/storage/pg/exporter/mapper",
        "@maven_logos//:com_google_inject_guice",
    ],
)