java_library(
    name = "validator",
    srcs = [
        "Validator.java",
    ],
    visibility = [
        "//app:__subpackages__",
        "//dev/logos/service/storage:__subpackages__",
    ],
    deps = [],
)
