java_library(
    name = "machine",
    srcs = [
        "Machine.java",
        "MachineContext.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//dev/logos/auth/principal",
        "@maven_logos//:io_grpc_grpc_api",
    ],
)
