apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: logos-eks-stack-backend-service-account
      containers:
        - name: backend
          image: logos-ecr-backend
          imagePullPolicy: Always
          env:
            - name: STORAGE_PG_BACKEND_JDBC_URL
              value: jdbc:postgresql://db-rw-service/logos?usessl=require&sslmode=verify-full&sslrootcert=/etc/ssl/certs/aws-rds-global-bundle.pem
            - name: STORAGE_PG_BACKEND_USER
              value: storage
            - name: LOGOS_SERVICE_JAR_CONFIG_PATH
              value: /app/config/service-jars
            - name: LOGOS_JAR_DIR
              value: /app/service-jars/
          ports:
            - containerPort: 8081
          livenessProbe:
            grpc:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: service-jars
              mountPath: /app/service-jars
      volumes:
        - name: config-volume
          configMap:
            name: logos-apps
        - name: service-jars
          persistentVolumeClaim:
            claimName: backend-rpc-service-jars
            readOnly: true