apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  ports:
    - port: 8081
      protocol: TCP
      nodePort: 30000
  selector:
    app: backend
  type: NodePort
