java_library(
    name = "mapper",
    srcs = [
        "PgTypeMapper.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:protobuf_java",
        "@maven_logos//:com_squareup_javapoet",
    ],
)
