apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-deployment
spec:
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: console-image:latest
          imagePullPolicy: Always
