java_library(
    name = "serviceaccount",
    srcs = [
        "ServiceAccountInterceptor.java",
    ],
    visibility = ["//app:__subpackages__"],
    deps = [
        "//app/auth/k8s/machine",
        "//dev/logos/auth/machine",
        "@maven_logos//:com_google_inject_guice",
        "@maven_logos//:io_grpc_grpc_api",
    ],
)
