apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30001
  selector:
    app: client
  type: NodePort
