java_library(
    name = "annotation",
    srcs = [
        "AwsAccountId.java",
        "AwsRegion.java",
        "StackOutputsJson.java",
    ],
    visibility = ["//visibility:public"],
    deps = ["@maven_logos//:com_google_inject_guice"],
)
