java_library(
    name = "cookie",
    srcs = [
        "CookieServerInterceptor.java",
    ],
    visibility = ["//app:__subpackages__"],
    deps = [
        "@maven_logos//:com_google_code_gson_gson",
        "@maven_logos//:io_grpc_grpc_api",
        "@maven_logos//:io_grpc_grpc_context",
    ],
)
