apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-controller
subjects:
  - kind: ServiceAccount
    name: app-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: app-controller-role
  apiGroup: rbac.authorization.k8s.io