apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.logos.dev
spec:
  group: logos.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                web-bundle:
                  type: string
                rpc-servers:
                  type: array
                  items:
                    type: object
                    required:
                      - domain
                      - service-name
                    properties:
                      domain:
                        type: string
                      service-name:
                        type: string
                volumes:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - size
                    properties:
                      name:
                        type: string
                      size:
                        type: string
                        pattern: "^\\d+([KkMmGgTt]i?)?"
  scope: Namespaced
  names:
    plural: apps
    singular: app
    kind: App
    shortNames:
      - app