load("//bzl:defs.bzl", "module")

module(
    name = "module",
    srcs = ["ClientModule.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//dev/logos/client/interceptor",
        "@maven_logos//:io_grpc_grpc_api",
    ],
)
