java_library(
    name = "module",
    srcs = [
        "ExportModule.java",
    ],
    visibility = ["//dev/logos/service/storage/pg:__subpackages__"],
    deps = [
        "//dev/logos/service/storage/pg/exporter/module/annotation",
        "@maven_logos//:com_google_inject_guice",
    ],
)
