java_library(
    name = "database_module",
    srcs = ["DatabaseModule.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//dev/logos/stack/service/storage/pg",
        "@maven//:com_google_inject_guice",
        "@maven//:com_zaxxer_HikariCP",
        "@maven//:dnsjava_dnsjava",
        "@maven//:javax_inject_javax_inject",
        "@maven//:org_postgresql_postgresql",
        "@maven//:software_amazon_awssdk_auth",
        "@maven//:software_amazon_awssdk_rds",
        "@maven//:software_amazon_awssdk_regions",
        "@maven//:software_amazon_awssdk_sso",
        "@maven//:software_amazon_awssdk_ssooidc",
        "@maven//:software_amazon_awssdk_utils",
    ],
)
