apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy
  name: envoy-service
spec:
  ports:
    - port: 8081
      protocol: TCP
      nodePort: 30003
  selector:
    app: envoy
  type: NodePort