java_library(
    name = "user",
    srcs = [
        "AuthenticatedUser.java",
    ],
    visibility = [
        "//app:__subpackages__",
    ],
    deps = [
        "//dev/logos/user",
        "@maven//:io_jsonwebtoken_jjwt_api",
    ],
)
