java_library(
    name = "service",
    srcs = ["Service.java"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//dev/logos/service/storage/validator",
        "//dev/logos/user",
        "@io_grpc_grpc_java//api",
        "@io_grpc_grpc_java//stub",
    ],
)
