java_library(
    name = "channel_library",
    srcs = ["ClientFactory.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@maven_logos//:io_grpc_grpc_api",
        "@maven_logos//:io_grpc_grpc_stub",
    ],
)
