java_library(
    name = "descriptor",
    srcs = [
        "ColumnDescriptor.java",
        "DerivedFieldDescriptor.java",
        "DerivedFieldParameterDescriptor.java",
        "ExportedIdentifier.java",
        "QualifierDescriptor.java",
        "QualifierParameterDescriptor.java",
        "SchemaDescriptor.java",
        "TableDescriptor.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@maven_logos//:com_google_guava_guava",
        "@maven_logos//:com_squareup_javapoet",
    ],
)