java_library(
    name = "descriptor",
    srcs = [
        "ColumnDescriptor.java",
        "ExportedIdentifier.java",
        "QualifierDescriptor.java",
        "QualifierParameterDescriptor.java",
        "SchemaDescriptor.java",
        "TableDescriptor.java",
    ],
    visibility = ["//dev/logos/service/storage/pg/exporter:__subpackages__"],
    deps = [
        "//dev/logos/service/storage/pg",
        "@maven_logos//:com_google_guava_guava",
        "@maven_logos//:com_squareup_javapoet",
    ],
)