apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: certificates@logos.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: logos-ingress-tls
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx