load("@aspect_rules_js//npm:defs.bzl", "npm_package")

npm_package(
    name = "npm",
    srcs = [
        "//:package.json",
        "//app/auth/cognito/web",
    ],
    package = "@logos/app-auth-cognito",
    visibility = ["//visibility:public"],
)
