apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
      - dev.digits.rip
      - dev.logos.dev
      - dev.rep.dev
    secretName: ingress-tls
  rules:
    - host: dev.digits.rip
      http:
        paths:
          - path: /services(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: envoy-service
                port:
                  number: 8081
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 8080
