java_library(
    name = "annotation",
    srcs = [
        "BuildDir.java",
        "BuildPackage.java",
    ],
    visibility = ["//dev/logos/service/storage/pg:__subpackages__"],
    deps = [
        "@maven_logos//:com_google_inject_guice",
    ],
)
