apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    email: certificates@logos.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: logos-gateway-tls
    solvers:
      - dns01:
          route53:
            region: us-east-2