apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    email: certificates@logos.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: logos-gateway-tls
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - namespace: default
                name: logos-gateway
                kind: Gateway