java_library(
    name = "user",
    srcs = [
        "NotAuthenticated.java",
        "User.java",
        "UserContext.java",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@maven_logos//:io_grpc_grpc_api",
        "@maven_logos//:io_grpc_grpc_context",
    ],
)
