java_library(
    name = "user",
    srcs = [
        "AnonymousUser.java",
        "NotAuthenticated.java",
        "User.java",
        "UserContext.java",
    ],
    visibility = [
        "//app:__subpackages__",
        "//dev/logos:__subpackages__",
    ],
    deps = [
        "@io_grpc_grpc_java//context",
    ],
)
