java_library(
    name = "machine",
    srcs = [
        "ServiceAccountMachine.java",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//dev/logos/auth/machine",
        "@maven_logos//:io_grpc_grpc_api",
        "@maven_logos//:io_jsonwebtoken_jjwt_api",
    ],
)
