java_library(
    name = "twilio",
    srcs = ["TwilioModule.java"],
    visibility = [
        "//app:__subpackages__",
    ],
    deps = [
        "@maven//:com_google_inject_guice",
        "@maven//:com_twilio_sdk_twilio",
        "@maven//:javax_inject_javax_inject",
    ],
)
