java_library(
    name = "twilio",
    srcs = ["TwilioModule.java"],
    visibility = [
        "//app:__subpackages__",
    ],
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_inject_guice",
        "@maven//:com_twilio_sdk_twilio",
        "@maven//:software_amazon_awssdk_secretsmanager",
    ],
)
