load("//bzl:prompt.bzl", "prompt")

prompt("""
transact is an editor for Bitcoin transactions. It allows an authenticated user to
track the state of Bitcoin addresses. It allows them to draft new unsigned Bitcoin
transactions which they can export and sign themselves using a different tool.

This tool is intended to be usable by both advanced and novice users.
""")
