java_library(
    name = "channel_library",
    srcs = ["ClientFactory.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@io_grpc_grpc_java//api",
        "@io_grpc_grpc_java//stub",
    ],
)
