java_library(
    name = "database_module",
    srcs = ["DatabaseModule.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//dev/logos/stack/service/storage/pg",
        "@maven//:com_google_inject_guice",
        "@maven//:com_zaxxer_HikariCP",
        "@maven//:javax_inject_javax_inject",
        "@maven//:org_postgresql_postgresql",
    ],
)
