java_library(
    name = "pg",
    srcs = glob([
        "*.java",
    ]),
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@maven_logos//:com_google_protobuf_protobuf_java",
        "@maven_logos//:org_jdbi_jdbi3_core",
        "@maven_logos//:org_jdbi_jdbi3_postgres",
    ],
)
