java_library(
    name = "module",
    srcs = [
        "ModuleLoader.java",
    ],
    plugins = [
        "//dev/logos/app/register:module",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//dev/logos/app/register:module_library",
        "@maven_logos//:com_google_code_gson_gson",
        "@maven_logos//:com_google_inject_guice",
        "@maven_logos//:org_slf4j_slf4j_api",
        "@maven_logos//:org_slf4j_slf4j_simple",
    ],
)
