java_library(
    name = "stack",
    srcs = [
        "EcrModule.java",
        "EksModule.java",
        "RdsModule.java",
        "RootConstructId.java",
        "VpcModule.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@maven_logos//:com_google_inject_guice",
        "@maven_logos//:software_amazon_awscdk_aws_cdk_lib",
        "@maven_logos//:software_amazon_awscdk_cdk_lambda_layer_kubectl_v30",
        "@maven_logos//:software_amazon_awssdk_auth",
        "@maven_logos//:software_amazon_awssdk_iam",
        "@maven_logos//:software_amazon_awssdk_sso",
        "@maven_logos//:software_amazon_awssdk_ssooidc",
        "@maven_logos//:software_amazon_awssdk_sts",
        "@maven_logos//:software_constructs_constructs",
    ],
)
