java_library(
    name = "worker",
    srcs = [
        "Worker.java",
        "WorkerState.java",
    ],
    visibility = ["//visibility:public"],
    deps = ["@maven_logos//:com_google_guava_guava"],
)
