java_library(
    name = "data",
    srcs = [
        "CognitoHostConfig.java",
        "CognitoHostSecret.java",
    ],
    visibility = [
        "//app/auth/module:__pkg__",
        "//app/auth/service:__pkg__",
    ],
)
